chore: cleanup
Signed-off-by: jeluard <jeluard@users.noreply.github.com>

diff --git a/app/Makefile b/app/Makefile
--- a/app/Makefile
+++ b/app/Makefile
@@ -2,8 +2,12 @@ run-simulator:
 # If on OSX, do `export LIBRARY_PATH="$LIBRARY_PATH:$(brew --prefix)/lib"`
 	cargo run --no-default-features --features simulator
 
-build-rpi:
-	cross build --release --target aarch64-unknown-linux-musl --features display_hat --no-default-features
+build-pi:
+	cross build --release --target aarch64-unknown-linux-musl
 
-upload-rpi: build-rpi
-	scp target/aarch64-unknown-linux-musl/release/app ${SCP_TARGET}
+upload-pi: build-pi
+	@if [ -z "$${SCP_TARGET}" ]; then \
+		echo "Error: SCP_TARGET is not set!"; \
+		exit 1; \
+	fi
+	scp target/aarch64-unknown-linux-musl/release/amaru-pi ${SCP_TARGET}
